/* Human Remedy Observatory: local, read-only exploration of versioned data. */
(() => {
  'use strict';
  const A = window.RemedyAnalysis;
  const $ = id => document.getElementById(id);
  const NS = 'http://www.w3.org/2000/svg';
  const C = {Public:'#096b68',Private:'#896815',Mixed:'#5c6370',Favorable:'#096b68',Adverse:'#a24b3d',Legacy:'#896815',Modern:'#096b68',ink:'#172523',muted:'#58645e',line:'#cdd1c7',pale:'#e4eee8'};
  const SECTORS=['Public','Private','Mixed'],DIRECTIONS=['Favorable','Mixed','Adverse'];
  const TOPICS=['Evidence and data','Classification','Authority and rules','Notice and hearing','Remedy access','Design and components','Capacity and delay','Incentives and independence'];
  const state={view:'atlas',cases:[],rows:[],selected:'miller_pate',registry:[],interventions:[],corpus:{},errors:[]};
  function node(tag,attrs={},text) { const n=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')n.className=v;else n.setAttribute(k,v);}if(text!==undefined)n.textContent=text;return n; }
  function svgNode(tag,attrs={},text) { const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n; }
  function el(tag,cls,text){return node(tag,cls?{class:cls}:{},text);}
  function p(text,cls='plot-note'){return el('p',cls,text);}
  function add(parent,...children){children.filter(Boolean).forEach(c=>parent.appendChild(c));return parent;}
  function safeLink(label,url){try{const u=new URL(url,location.href);if(!['http:','https:'].includes(u.protocol))return el('span','',label);const a=node('a',{href:u.href,target:'_blank',rel:'noopener noreferrer'},label);return a;}catch{return el('span','',label);}}
  function textSVG(svg,x,y,text,attrs={}){svg.appendChild(svgNode('text',{x,y,...attrs},text));}
  function line(svg,x1,y1,x2,y2,attrs={}){svg.appendChild(svgNode('line',{x1,y1,x2,y2,...attrs}));}
  function titleSVG(n,text){n.appendChild(svgNode('title',{},text));return n;}
  function selection(){return{country:$('country').value,sector:$('sector').value,technology:$('technology').value,search:$('search').value,habeas:$('habeas').checked,alternative:$('alternative').checked,comparator:$('comparator').checked};}
  function restoreViewFromURL(){
    const saved=A.parseViewState(location.search,state.cases);
    state.view=saved.view;state.selected=saved.selected;
    for(const key of ['country','sector','technology'])$(key).value=saved.selection[key];
    $('search').value=saved.selection.search;
    for(const key of ['habeas','alternative','comparator'])$(key).checked=saved.selection[key];
  }
  function persistViewURL(){
    const url=new URL(location.href);
    url.search=A.buildViewParams({view:state.view,selection:selection(),selected:state.selected}).toString();
    history.replaceState(null,'',url.pathname+url.search+url.hash);
    return url.href;
  }
  function renderViewSummary(){
    const names={atlas:'Case atlas',relationships:'Relationships',corpus:'Larger corpus',research:'Research & legislation'};
    const isAtlas=['atlas','relationships'].includes(state.view),s=selection();
    $('view-toolbar').hidden=false;
    $('current-view-summary').textContent='Current view: '+names[state.view]+(isAtlas?` · ${state.rows.length} selected case families`:'');
    const chips=$('view-chips');chips.replaceChildren();
    let labels;
    if(isAtlas){
      const selected=state.rows.find(c=>c.id===state.selected);
      labels=[s.country==='all'?'All jurisdictions':s.country==='US'?'United States':s.country,s.sector==='all'?'All sectors':s.sector,s.technology==='all'?'All system types':s.technology,s.habeas?'Habeas only':'All procedural routes',s.alternative?'Alternative sector coding':'Baseline sector coding',s.comparator?'Comparator included':'Comparator excluded'];
      if(s.search)labels.push('Search: '+s.search);
      if(selected)labels.push('Inspecting: '+(selected.short||selected.name));
    }else if(state.view==='corpus')labels=['Separate SCDB corpus','Atlas filters not applied','Coverage, not human win rates'];
    else labels=['Ranked dashboard roadmap','Proposed safeguards','Interventions untested'];
    labels.forEach(label=>chips.appendChild(el('span','badge',label)));
    $('copy-link-status').textContent='';$('copy-link-fallback').hidden=true;
    $('view-url').value=persistViewURL();
  }
  async function copyViewLink(){
    const url=persistViewURL();
    try{
      if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');
      await navigator.clipboard.writeText(url);
      $('copy-link-status').textContent='Local view link copied. It requires the same local server port and data.';
      $('copy-link-fallback').hidden=true;
    }catch{
      $('view-url').value=url;$('copy-link-fallback').hidden=false;
      $('copy-link-status').textContent='Automatic copying is unavailable. Select and copy the local URL below.';
      $('view-url').focus();$('view-url').select();
    }
  }
  function sector(c){return A.sectorOf(c,$('alternative').checked);}
  function metric(label,value){return add(el('div','metric'),el('div','value',value),el('div','label',label));}
  function empty(parent,message='No cases match this selection. Change a filter or reset the selection.'){add(parent,p(message,'empty'));}
  function button(label,fn){const b=node('button',{type:'button'},label);b.addEventListener('click',fn);return b;}
  function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=node('a',{href:url,download:name});document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportSelection(format){const meta={exported_at:new Date().toISOString(),source:'data/curated/cases.json',unit:'selected litigation family',selection:selection(),selected_count:state.rows.length,stored_record_count:state.cases.length,interpretation:'Purposive case atlas; not population success rates or causal effects'};if(format==='json')download('human-remedy-selection.json',JSON.stringify({metadata:meta,cases:state.rows},null,2),'application/json');else{const rows=state.rows.map(c=>({...c,selected_sector:sector(c),selection_metadata:JSON.stringify(meta)}));download('human-remedy-selection.csv',A.toCSV(rows,['id','name','country','year','last_year','sector','selected_sector','technology','direction','stage','habeas_vehicle','tags','summary','limit','implementation','restoration_note','sources','selection_metadata']),'text/csv;charset=utf-8');}}
  function panel(parent,title,note,{wide=false}={}){const section=el('section','plot-panel'+(wide?' wide':''));const head=add(el('div','plot-head'),el('h3','',title));add(section,head,p(note));parent.appendChild(section);return{section,head};}
  function chart(container,width,height,label){const wrap=el('div','svg-wrap');const svg=svgNode('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':label});add(wrap,svg);container.section.appendChild(wrap);container.head.appendChild(button('Export SVG',()=>{const clone=svg.cloneNode(true);clone.setAttribute('xmlns',NS);const style=svgNode('style',{},'text{font-family:system-ui,sans-serif;font-size:12px;fill:#172523}.tick,.axis-title{font-size:11px;fill:#58645e}.grid{stroke:#e6e9e1;stroke-width:1}.chart-frame{fill:none;stroke:#cdd1c7;stroke-width:1}');clone.prepend(style);clone.insertBefore(svgNode('rect',{width:'100%',height:'100%',fill:'#fffefa'}),style);download(label.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.svg',new XMLSerializer().serializeToString(clone),'image/svg+xml');}));return svg;}
  function legend(parent,keys){const l=el('div','legend');keys.forEach(k=>{const item=el('span');const sw=el('i','swatch');sw.style.background=C[k]||C.ink;add(item,sw,document.createTextNode(k));l.appendChild(item);});parent.appendChild(l);}
  function rect(svg,x,y,w,h,fill,label,handler){const r=titleSVG(svgNode('rect',{x,y,width:w,height:h,fill,rx:2}),label);if(handler){r.setAttribute('tabindex','0');r.setAttribute('role','button');r.setAttribute('class','focusable');r.setAttribute('aria-label',label);r.addEventListener('click',handler);r.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handler();}});}svg.appendChild(r);return r;}
  function bars(parent,title,note,items,{unit='Selected litigation families (count)',maxValue,wide=false,valueFormat=v=>String(v)}={}){
    const panelEl=panel(parent,title,note,{wide});if(!items.length){empty(panelEl.section,'No recorded values for the current selection.');return;}const W=660,L=215,R=58,T=22,B=50,row=30,H=T+B+row*items.length,plotW=W-L-R,max=maxValue??Math.max(1,...items.map(d=>d.value));const svg=chart(panelEl,W,H,title);
    const tickValues=max===1&&unit.includes('similarity')?[0,.25,.5,.75,1]:[...new Set(Array.from({length:5},(_,i)=>Math.round(max*i/4)))];for(const v of tickValues){const x=L+plotW*v/max;line(svg,x,T,x,H-B,{class:'grid'});textSVG(svg,x,H-B+18,max===1&&unit.includes('similarity')?v.toFixed(2):String(v),{'text-anchor':'middle',class:'tick'});}svg.appendChild(svgNode('rect',{x:L,y:T,width:plotW,height:H-T-B,class:'chart-frame'}));
    items.forEach((d,i)=>{const y=T+i*row+5;textSVG(svg,L-10,y+14,d.label,{'text-anchor':'end'});rect(svg,L,y,plotW*d.value/max,21,d.color||C[d.label]||C.Public,`${d.label}: ${valueFormat(d.value)}`,d.onClick);textSVG(svg,L+plotW*d.value/max+7,y+15,valueFormat(d.value));});textSVG(svg,L+plotW/2,H-9,unit,{'text-anchor':'middle',class:'axis-title'});
  }
  function heatmap(parent,title,note,rowLabels,colLabels,value,{maxValue,unit='Selected litigation families (count)',format=v=>String(v),wide=false}={}){
    const box=panel(parent,title,note,{wide});const W=Math.max(570,210+colLabels.length*67),L=205,R=30,T=72,B=44,cw=(W-L-R)/colLabels.length,rh=37,H=T+B+rowLabels.length*rh;const svg=chart(box,W,H,title);const vals=rowLabels.flatMap(r=>colLabels.map(c=>value(r,c)));const max=maxValue??Math.max(1,...vals.filter(v=>v!=null));
    colLabels.forEach((c,j)=>{textSVG(svg,L+(j+.5)*cw,T-15,c,{'text-anchor':'middle',class:'tick'});});rowLabels.forEach((r,i)=>{textSVG(svg,L-10,T+i*rh+24,r,{'text-anchor':'end'});colLabels.forEach((c,j)=>{const v=value(r,c),opacity=v==null?0:0.1+0.9*v/max;rect(svg,L+j*cw+2,T+i*rh+2,cw-4,rh-4,'#096b68',`${r}; ${c}: ${v==null?'Not estimable':format(v)}`).setAttribute('fill-opacity',opacity);textSVG(svg,L+(j+.5)*cw,T+i*rh+24,v==null?'—':format(v),{'text-anchor':'middle',style:`fill:${v!=null&&v/max>.55?'#fffefa':'#172523'}`});});});textSVG(svg,L+(W-L-R)/2,H-13,unit,{'text-anchor':'middle',class:'axis-title'});return box;
  }
  function heading(parent,title,deck){add(parent,el('h2','section-title',title),p(deck,'section-deck'));}
  function grid(parent){const g=el('div','plot-grid');parent.appendChild(g);return g;}
  function selectCase(id){state.selected=id;const view=state.view;if(view==='atlas'||view==='relationships'){renderActive();const ins=document.querySelector('.inspector');if(ins)ins.scrollIntoView({behavior:'auto',block:'start'});}}
  function inspector(parent){const selected=state.rows.find(c=>c.id===state.selected)||state.rows[0];if(!selected)return;state.selected=selected.id;const box=el('section','inspector');const top=el('div','inspector-top');const label=el('label','', 'Inspect a case and its sources');const sel=node('select',{'aria-label':'Inspect case'});[...state.rows].sort((a,b)=>a.name.localeCompare(b.name)).forEach(c=>{const o=node('option',{value:c.id},c.name);o.selected=c.id===selected.id;sel.appendChild(o);});sel.addEventListener('change',()=>selectCase(sel.value));add(label,sel);add(top,el('h3','',selected.name),label);add(box,top,p(`${selected.country} · ${selected.year}${selected.last_year!==selected.year?' → '+selected.last_year:''} · ${sector(selected)} · ${selected.technology} · ${selected.direction}`,'meta'));const fields=el('div','inspector-grid');const entries=[['What the selected source establishes',selected.summary],['Interpretation limit',selected.limit],['Habeas route',selected.habeas_vehicle||'No actual habeas proceeding identified in this record.'],['Data / failure evidence',selected.data_status||selected.data_failure||'No separate data-failure status coded. Read the source and summary.'],['Holding scope',selected.holding_scope||'See the selected decision and interpretation limit.'],['Practical correction',selected.restoration_note||'No follow-up statement recorded.'],['Responsibility coding',selected.sector_note||'No sector note recorded.']];entries.forEach(([title,value])=>add(fields,add(el('div'),el('h4','',title),p(typeof value==='object'?JSON.stringify(value):String(value),'') )));const sources=add(el('div'),el('h4','', 'Sources'));const list=el('ul');(selected.sources||[]).forEach(s=>add(list,add(el('li'),safeLink(s.label,s.url))));add(sources,list);add(fields,sources);add(box,fields);const tags=el('div');(selected.tags||[]).forEach(t=>tags.appendChild(el('span','badge',t)));add(box,tags);parent.appendChild(box);}
  function table(parent,headers,rows){const wrap=el('div','table-wrap');const t=el('table'),thead=el('thead'),tr=el('tr');headers.forEach(h=>tr.appendChild(el('th','',h)));add(t,add(thead,tr));const body=el('tbody');rows.forEach(row=>{const r=el('tr');row.forEach(v=>{const td=el('td');if(v instanceof Node)td.appendChild(v);else td.textContent=v==null?'Not recorded':String(v);r.appendChild(td);});body.appendChild(r);});add(t,body);add(wrap,t);add(parent,wrap);}
  function renderAtlas(){const target=$('view-atlas');target.replaceChildren();heading(target,'Read the record before counting the result.','The unit is a selected litigation family. Filters change every atlas chart and export; this is not a random sample of disputes or a population success-rate estimate.');if(!state.rows.length){empty(target);return;}const g=grid(target),rows=state.rows;
    const fields=[['Source link',c=>(c.sources||[]).some(s=>s.url)],['Source summary',c=>!!c.summary],['Interpretation limit',c=>!!c.limit],['Responsibility note',c=>!!c.sector_note],['Correction follow-up note',c=>!!c.restoration_note],['Separate data-status field',c=>!!c.data_status],['Habeas route identified',c=>!!c.habeas_vehicle]];
    bars(g,'01 / Documentation coverage','A present field means documentation exists. It does not certify truth, completeness, or a system defect. Habeas routes apply only to the relevant subset.',fields.map(([label,fn])=>({label,value:rows.filter(fn).length})),{maxValue:rows.length});
    heatmap(g,'02 / Responsibility × selected result','Favorable, mixed, and adverse refer to the latest selected disposition for the human side. Cases with distinct histories remain separately inspectable.',SECTORS,DIRECTIONS,(s,d)=>rows.filter(c=>sector(c)===s&&c.direction===d).length);
    bars(g,'03 / What kind of result?','A hearing, judgment, settlement, and completed correction are different events. These are disposition categories, not levels on a single success scale.',Object.entries(A.counts(rows,'stage')).sort((a,b)=>b[1]-a[1]).map(([label,value])=>({label,value})),{});
    const known=rows.filter(c=>c.implementation==='Documented some restoration').length;
    bars(g,'10 / Practical correction reported','“Reported at some point” can predate the selected judgment. Unknown follow-up is not zero restoration, and these counts are not an implementation rate.',[{label:'Some restoration reported',value:known,color:C.Public},{label:'Not established in sources',value:rows.length-known,color:C.Mixed}],{maxValue:rows.length});
    const route=panel(g,'04 / Actual habeas routes','A habeas label is assigned from the procedural source, not inferred from imprisonment, bad data, or a favorable outcome.',{wide:true});const habeas=rows.filter(c=>c.habeas_vehicle);if(!habeas.length)empty(route.section,'No identified habeas proceedings in this selection.');else table(route.section,['Case','Public / private','Selected result','Procedural route'],habeas.map(c=>[button(c.name,()=>selectCase(c.id)),sector(c),c.direction,c.habeas_vehicle]));
    inspector(target);
    const catalogue=el('details');add(catalogue,el('summary','',`Browse all ${rows.length} selected case families`));table(catalogue,['Case','Country','System','Responsibility','Result','Selected stage'],rows.map(c=>[button(c.name,()=>selectCase(c.id)),c.country,c.technology,sector(c),c.direction,c.stage]));add(target,catalogue);
  }
  function renderTimeline(parent){const rows=[...state.rows].sort((a,b)=>a.year-b.year||a.name.localeCompare(b.name));const box=panel(parent,'08 / First and last selected legal anchors','Each row connects the first and last years represented by our selected sources. This is not time in custody, litigation duration, or time to remedy.',{wide:true});const W=1080,L=240,R=55,T=45,B=48,rowH=23,H=T+B+rows.length*rowH;const svg=chart(box,W,H,'Selected source timeline'),min=Math.min(...rows.map(c=>c.year)),max=Math.max(min+1,...rows.map(c=>c.last_year||c.year)),x=y=>L+(W-L-R)*(y-min)/(max-min);const step=Math.max(1,Math.ceil((max-min)/6/5)*5);const years=[min];for(let y=Math.ceil(min/step)*step;y<max;y+=step)if(y>min)years.push(y);years.push(max);years.forEach(y=>{line(svg,x(y),T-10,x(y),H-B,{class:'grid'});textSVG(svg,x(y),T-20,y,{'text-anchor':'middle',class:'tick'});});rows.forEach((c,i)=>{const y=T+i*rowH+9;textSVG(svg,L-10,y+4,c.short||c.name,{'text-anchor':'end',class:'tick'});line(svg,x(c.year),y,x(c.last_year||c.year),y,{stroke:C[sector(c)],'stroke-width':3});const dot=titleSVG(svgNode('circle',{cx:x(c.last_year||c.year),cy:y,r:6,fill:C[sector(c)],tabindex:0,role:'button',class:'focusable','aria-label':`${c.name}: ${c.year} to ${c.last_year||c.year}, ${c.direction}`}),`${c.name}: ${c.year} to ${c.last_year||c.year}; ${c.direction}`);dot.addEventListener('click',()=>selectCase(c.id));dot.addEventListener('keydown',e=>{if(e.key==='Enter'){selectCase(c.id);}});svg.appendChild(dot);});textSVG(svg,L+(W-L-R)/2,H-13,'Selected source year (calendar year)',{'text-anchor':'middle',class:'axis-title'});legend(box.section,SECTORS);}
  function renderDAG(parent){const box=panel(parent,'11 / Assumed causal structure','This diagram proposes relationships to scrutinize. Arrows are assumptions, not estimated effects. Published cases select on review and reporting, so this atlas alone cannot identify intervention effects.',{wide:true});const W=1000,H=340,svg=chart(box,W,H,'Assumed causal structure');const nodes=[{id:'context',x:20,y:45,w:210,t:'Context / severity / resources'},{id:'design',x:295,y:45,w:210,t:'Safeguard or design choice'},{id:'correction',x:570,y:45,w:210,t:'Verified practical correction'},{id:'access',x:295,y:205,w:210,t:'Access to review / litigation'},{id:'sample',x:705,y:205,w:240,t:'Appears in published collection'}];const by=Object.fromEntries(nodes.map(n=>[n.id,n]));const defs=svgNode('defs');add(defs,add(svgNode('marker',{id:'dag-arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'}),svgNode('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:C.muted})));svg.appendChild(defs);[['context','design'],['design','correction'],['context','access'],['context','correction'],['access','correction'],['access','sample'],['correction','sample']].forEach(([a,b])=>{const n=by[a],m=by[b];const x1=n.x+n.w/2,y1=n.y+52,x2=m.x+m.w/2,y2=m.y;if(n.y===m.y){const d=a==='context'&&b==='correction'?`M ${n.x+n.w/2} ${n.y} V 15 H ${m.x+m.w/2} V ${m.y}`:`M ${n.x+n.w} ${n.y+26} H ${m.x}`;svg.appendChild(svgNode('path',{d,fill:'none',stroke:C.muted,'stroke-width':1.5,'marker-end':'url(#dag-arrow)'}));}else line(svg,x1,y1,x2,y2,{stroke:C.muted,'stroke-width':1.5,'marker-end':'url(#dag-arrow)'});});nodes.forEach(n=>{rect(svg,n.x,n.y,n.w,52,n.id==='sample'?'#f0e7cc':C.pale,n.t);textSVG(svg,n.x+n.w/2,n.y+31,n.t,{'text-anchor':'middle',style:'font-size:12px'});});textSVG(svg,22,H-30,'Unit: assumed relationships among constructs; no statistical scale.',{class:'axis-title'});}
  function renderRelationships(){const target=$('view-relationships');target.replaceChildren();heading(target,'Explore relationships without mistaking them for causes.','Patterns describe our chosen cases and their annotations. Sector and outcome are deliberately excluded from topic-similarity features; unmarked topics are not proof that a mechanism was absent.');if(!state.rows.length){empty(target);return;}const g=grid(target),rows=state.rows;
    heatmap(g,'05 / System type × responsibility','Physical includes product components and forensic evidence. Computerized does not imply that a software defect was proved.',['Physical','Administrative','Computerized'],SECTORS,(t,s)=>rows.filter(c=>c.technology===t&&sector(c)===s).length);
    heatmap(g,'06 / Challenged topics × responsibility','Topics overlap and count allegations or issues selected for analysis. They are not a court-verified failure taxonomy.',TOPICS,SECTORS,(t,s)=>rows.filter(c=>(c.tags||[]).includes(t)&&sector(c)===s).length);
    const topicKey=TOPICS.map((_,i)=>'T'+(i+1));const j=heatmap(g,'07 / Topic co-occurrence similarity','Jaccard = families sharing both topics / families carrying either topic. This summarizes annotation overlap; it does not measure causation.',topicKey,topicKey,(a,b)=>{const x=rows.filter(c=>(c.tags||[]).includes(TOPICS[topicKey.indexOf(a)])).map(c=>c.id),y=rows.filter(c=>(c.tags||[]).includes(TOPICS[topicKey.indexOf(b)])).map(c=>c.id);return A.jaccard(x,y);},{maxValue:1,unit:'Jaccard similarity (0–1; — means no union)',format:v=>v.toFixed(2)});add(j.section,p(topicKey.map((k,i)=>`${k}: ${TOPICS[i]}`).join(' · ')));
    const selected=rows.find(c=>c.id===state.selected)||rows[0];bars(g,`07b / Cases with similar topic annotations`,`Anchor: ${selected.name}. Only topic tags enter the similarity calculation. Ties are sorted alphabetically; this is exploratory retrieval, not validated clustering.`,A.nearestCases(selected,rows).slice(0,8).map(n=>({label:n.case.short||n.case.name,value:n.similarity,onClick:()=>selectCase(n.case.id)})),{maxValue:1,unit:'Jaccard topic similarity (0–1)',valueFormat:v=>v.toFixed(2)});
    const sensitivity=panel(g,'09 / Classification sensitivity','Both codings use the same currently selected families. Values summarize categorical association, not causal influence, variance explained, significance, or confidence intervals.',{wide:true});const testKeys=[['Responsibility × disposition','stage'],['Responsibility × system type','technology'],['Responsibility × selected result','direction']];table(sensitivity.section,['Relationship','Baseline Cramér’s V','Alternative Cramér’s V','Interpretation'],testKeys.map(([name,key])=>{const b=A.cramerV(rows,c=>A.sectorOf(c,false),key),a=A.cramerV(rows,c=>A.sectorOf(c,true),key);return[name,b==null?'Not estimable':b.toFixed(3),a==null?'Not estimable':a.toFixed(3),'Descriptive, fixed selection; no p-value'];}));
    const sensSvg=chart(sensitivity,960,255,'Classification sensitivity comparison');
    const sx=v=>290+610*v;for(const v of [0,.25,.5,.75,1]){line(sensSvg,sx(v),24,sx(v),190,{class:'grid'});textSVG(sensSvg,sx(v),211,v.toFixed(2),{'text-anchor':'middle',class:'tick'});}
    testKeys.forEach(([label,key],i)=>{const y=32+i*52;textSVG(sensSvg,280,y+21,label,{'text-anchor':'end'});for(const [alt,dy,color] of [[false,0,C.Public],[true,21,C.Private]]){const v=A.cramerV(rows,c=>A.sectorOf(c,alt),key);if(v==null)textSVG(sensSvg,300,y+dy+13,'Not estimable',{class:'tick'});else{rect(sensSvg,290,y+dy,610*v,16,color,`${label}; ${alt?'alternative':'baseline'}: ${v.toFixed(3)}`);textSVG(sensSvg,sx(v)+6,y+dy+13,v.toFixed(3),{class:'tick'});}}});
    textSVG(sensSvg,590,239,'Descriptive Cramér’s V (0–1); teal = baseline, gold = alternative',{'text-anchor':'middle',class:'axis-title'});
    renderTimeline(g);renderDAG(g);inspector(target);
  }
  function corpusLine(parent,rows){const box=panel(parent,'C1 / Court-term coverage','Counts describe the frozen source files. Court jurisdiction, publication practices, and coding change across eras. Counts are not incidence or failure rates.',{wide:true}),W=1060,H=330,L=65,R=25,T=30,B=60,svg=chart(box,W,H,'SCDB Court term coverage');const terms=rows.map(r=>Number(r.term)),values=rows.map(r=>Number(r.case_count)),min=Math.min(...terms),max=Math.max(...terms),vmax=Math.max(...values),x=v=>L+(W-L-R)*(v-min)/(max-min),y=v=>H-B-(H-T-B)*v/vmax;for(let i=0;i<=4;i++){const v=vmax*i/4;line(svg,L,y(v),W-R,y(v),{class:'grid'});textSVG(svg,L-10,y(v)+4,Math.round(v),{'text-anchor':'end',class:'tick'});}for(let t=1800;t<=max;t+=25)textSVG(svg,x(t),H-B+22,t,{'text-anchor':'middle',class:'tick'});for(const period of ['Legacy','Modern']){const data=rows.filter(r=>r.period===period).sort((a,b)=>Number(a.term)-Number(b.term));const d=data.map((r,i)=>`${i?'L':'M'} ${x(+r.term)} ${y(+r.case_count)}`).join(' ');svg.appendChild(svgNode('path',{d,fill:'none',stroke:C[period],'stroke-width':2}));for(const r of data){const dot=titleSVG(svgNode('circle',{cx:x(+r.term),cy:y(+r.case_count),r:2,fill:C[period]}),`${r.term}: ${r.case_count} ${period} source cases`);svg.appendChild(dot);}}textSVG(svg,L,H-13,'Court term (year)',{class:'axis-title'});textSVG(svg,L,T-12,'Source cases (count)',{class:'axis-title'});legend(box.section,['Legacy','Modern']);}
  function renderCorpus(){const target=$('view-corpus');target.replaceChildren();heading(target,'A larger source corpus answers different questions.','The Supreme Court Database provides a broad, reproducible research frame. It does not contain all US petitions, operational-load measures, or a verified human-remedy outcome for every record. Case-atlas filters do not apply to this separate corpus.');const corpus=state.corpus;if(!corpus.summary){empty(target,'SCDB coverage files are unavailable. The case atlas remains usable. Run the documented source workflow to restore the aggregate reports.');return;}add(target,p('SCDB partyWinning identifies the party petitioning the Supreme Court, which may be the government. It must not be interpreted as “the affected human won.” Habeas issue codes locate candidates for review; they do not establish procedural habeas status.','notice'));const g=grid(target);
    if(corpus.coverage?.length)corpusLine(g,corpus.coverage);
    if(corpus.issues?.length){const labels=[...new Set(corpus.issues.map(r=>r.issue_area))];heatmap(g,'C2 / Source issue composition','SCDB issue-area labels describe the source coding. Different era totals and jurisdiction mean these cells should not be compared as population risks.',labels,['Legacy','Modern'],(a,b)=>Number(corpus.issues.find(r=>r.issue_area===a&&r.period===b)?.case_count??0),{unit:'Source cases (count)'});}
    if(corpus.blanks?.length){const labels=[...new Set(corpus.blanks.map(r=>r.field))];heatmap(g,'C3 / Blank-field coverage','Blanks can mean not applicable. They are not proof of faulty evidence, invalid adjudication, or poor source quality.',labels,['Legacy','Modern'],(a,b)=>{const r=corpus.blanks.find(r=>r.field===a&&r.period===b);return r?Number(r.blank_percent):null;},{maxValue:100,unit:'Blank entries / era records (%)',format:v=>v.toFixed(2)+'%'});}
    if(corpus.habeas?.length){const eras=[...new Set(corpus.habeas.map(r=>r.era))];heatmap(g,'C4 / Habeas issue candidates by era','The two issue codes find a review queue. They do not verify that each case arose on a habeas petition and they omit some actual habeas proceedings.',eras,['10020','90040'],(a,b)=>{const r=corpus.habeas.find(r=>r.era===a&&r.issue_code===b);return r?Number(r.candidate_count):null;},{unit:'Issue-code candidates (count)'});}
    add(target,p('Source: SCDB legacy 07 and modern 2026_01; aggregate reports are versioned in reports/scdb. Raw redistribution is not implied by this workbench.','method-note'));add(target,safeLink('SCDB provenance and acquisition notes',new URL('../SCDB_DATA.md',location.href).href));
  }
  function renderResearch(){const target=$('view-research');target.replaceChildren();heading(target,'Turn a pattern into a testable safeguard.','Observed case patterns motivate questions. A proposed intervention needs an operational outcome, a defensible comparison, explicit safeguards, and a decision rule before it can support a legislative effectiveness claim.');add(target,p('These proposals have not been tested by the historical atlas. Zero observed harm in a finite study does not prove zero future risk. Hypotheses developed after exploration need independent evaluation data or a properly reserved holdout.','notice'));const links=el('div','masthead-links');add(links,safeLink('Critical path and work packages',new URL('../docs/CRITICAL_PATH.md',location.href).href),safeLink('Legislative test specifications',new URL('../docs/LEGISLATIVE_TESTS.md',location.href).href),safeLink('Analysis plan',new URL('../methods/ANALYSIS_PLAN.md',location.href).href));add(target,links);
    const strip=el('div','event-strip');['Explore & audit','Specify hypothesis','Freeze plan','Evaluate independently','Report uncertainty','Correct and retest'].forEach(v=>strip.appendChild(el('span','',v)));add(target,strip);
    add(target,el('h3','', 'Dashboard roadmap, ordered by measurement readiness'));
    if(state.registry.length){table(target,['Priority / view','Research question','Status','Required measurements','Limits / next work'],[...state.registry].sort((a,b)=>a.rank-b.rank).map(v=>{const status=el('span','badge '+(v.status==='available'?'status-ready':'status-needed'),v.status);return[`${String(v.rank).padStart(2,'0')} · ${v.title}`,v.question,status,(v.required_fields||[]).join(', '),[...(v.limitations||[]),v.work_package?'Work package: '+v.work_package:''].filter(Boolean).join(' ')];}));}else empty(target,'The dashboard registry has not loaded. The available atlas and corpus views above still operate.');
    add(target,el('h3','', 'Interventions, hypotheses, and proposed legislative duties'));
    const cards=el('div','research-grid');state.interventions.forEach(v=>{const card=el('article','research-card');add(card,el('span','badge',v.status||'Proposed; untested'),el('h3','',`${v.id} · ${v.title}`));const dl=el('dl');const fields=[['Mechanism',v.mechanism],['Intervention',v.intervention],['Measured outcome',v.outcome],['Unit',v.unit],['Null hypothesis',v.null_hypothesis],['Alternative hypothesis',v.alternative_hypothesis],['Study design',v.design],['Proposed legislative clause',v.legislative_clause]];fields.forEach(([k,val])=>{if(val)add(dl,el('dt','',k),el('dd','',typeof val==='object'?JSON.stringify(val):val));});add(card,dl);if(v.guardrails?.length){add(card,el('h4','', 'Guardrails'));const ul=el('ul');v.guardrails.forEach(t=>ul.appendChild(el('li','',t)));add(card,ul);}if(v.sources?.length){const ul=el('ul');v.sources.forEach(s=>add(ul,add(el('li'),safeLink(s.label,s.url))));add(card,ul);}add(cards,card);});add(target,cards);if(!state.interventions.length)empty(target,'Intervention specifications are not available in this checkout yet.');
    add(target,p('Current evidence supports descriptive case comparisons and mechanism hypotheses. It does not yet estimate causal effects, certify a governing system as safe, or convert the book into universally admissible court evidence.','method-note'));
  }
  function updateMetrics(){const m=$('metrics');m.replaceChildren();if(state.view==='corpus'&&state.corpus.summary){const s=state.corpus.summary;add(m,metric('Frozen source case records',Number(s.source_case_count).toLocaleString()),metric('Legacy source records',Number(s.legacy_count).toLocaleString()),metric('Modern source records',Number(s.modern_count).toLocaleString()),metric('Issue-code candidates; unverified route',Number(s.habeas_issue_10020_count+s.habeas_issue_90040_count).toLocaleString()));}else if(state.view==='research'){add(m,metric('Ranked research views',state.registry.length||'—'),metric('Views available now',state.registry.filter(v=>v.status==='available').length||'—'),metric('Proposed interventions',state.interventions.length||'—'),metric('Causal effects established','None'));}else{add(m,metric('Selected litigation families',state.rows.length),metric('Identified habeas proceedings',state.rows.filter(c=>c.habeas_vehicle).length),metric('Distinct coded system groups',new Set(state.rows.map(c=>c.system_group||c.id)).size),metric('Families with some restoration reported',state.rows.filter(c=>c.implementation==='Documented some restoration').length));}}
  function renderActive(){state.rows=A.filterCases(state.cases,selection());const atlas=['atlas','relationships'].includes(state.view);$('atlas-controls').hidden=!atlas;$('selection-note').hidden=!atlas;$('selection-note').textContent=`Showing ${state.rows.length} of ${state.cases.length} stored records · ${selection().country==='all'?'all jurisdictions':selection().country==='US'?'United States':selection().country} · ${selection().alternative?'alternative':'baseline'} responsibility coding. Organization comparator ${selection().comparator?'included':'excluded'}. Counts reflect this selection; families can share a challenged system.`;['atlas','relationships','corpus','research'].forEach(v=>$('view-'+v).hidden=v!==state.view);document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);if(b.dataset.view===state.view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});updateMetrics();({atlas:renderAtlas,relationships:renderRelationships,corpus:renderCorpus,research:renderResearch}[state.view])();renderViewSummary();}
  async function read(url,json=true,required=false){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return json?await r.json():A.parseCSV(await r.text());}catch(e){state.errors.push(`${url}: ${e.message}`);if(required)throw e;return null;}}
  async function init(){try{const paths=['../data/curated/cases.json','../data/research/dashboard-registry.json','../data/research/interventions.json','../reports/scdb/summary.json','../reports/scdb/coverage_by_term.csv','../reports/scdb/issue_mix.csv','../reports/scdb/blank_fields.csv','../reports/scdb/habeas_issue_candidates_by_era.csv'];const result=await Promise.all(paths.map((url,i)=>read(url,i<4,i===0)));if(!Array.isArray(result[0])||!result[0].every(c=>c&&c.id&&c.name&&Array.isArray(c.tags)))throw new Error('The curated case file has an unexpected schema.');state.cases=result[0];state.registry=Array.isArray(result[1])?result[1]:[];state.interventions=Array.isArray(result[2])?result[2]:[];state.corpus={summary:result[3],coverage:result[4],issues:result[5],blanks:result[6],habeas:result[7]};const countries=[...new Set(state.cases.map(c=>c.country))].filter(c=>c!=='US').sort();countries.forEach(c=>$('country').appendChild(node('option',{value:c},c)));restoreViewFromURL();if(state.errors.length){$('load-status').textContent=`Core case data loaded. ${state.errors.length} optional research file(s) are unavailable; affected views identify the missing data.`;$('load-status').className='notice';}else $('load-status').hidden=true;['country','sector','technology','habeas','alternative','comparator'].forEach(id=>$(id).addEventListener('change',renderActive));$('search').addEventListener('input',renderActive);$('reset').addEventListener('click',()=>{$('country').value='US';$('sector').value='all';$('technology').value='all';$('search').value='';['habeas','alternative','comparator'].forEach(id=>$(id).checked=false);renderActive();});$('download-json').addEventListener('click',()=>exportSelection('json'));$('download-csv').addEventListener('click',()=>exportSelection('csv'));$('copy-view-link').addEventListener('click',copyViewLink);window.addEventListener('popstate',()=>{restoreViewFromURL();renderActive();});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;renderActive();}));renderActive();}catch(e){$('load-status').className='notice';$('load-status').textContent=`Cannot load the case data: ${e.message}. Launch the workbench with the documented local server; opening index.html directly does not provide the required relative data URLs.`;}}
  init();
})();
